[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]

[target.mipsel-unknown-linux-musl]
linker = "/tmp/mipsel-linux-muslsf-cross/bin/mipsel-linux-muslsf-gcc"
rustflags = ["-C", "target-feature=+soft-float"]
